import type { Aluguel, Imovel, Pessoa } from '@imob/shared';

export const fakePessoas: Pessoa[] = [
  {
    id: 'pes-1',
    codigo: 'P001',
    nome: 'Carlos Henrique Almeida',
    documentoFiscal: '123.456.789-00',
    identidade: 'MG-10.203.405',
    dataNascimento: '1982-04-11',
    cidadeNascimento: 'Belo Horizonte',
    pais: 'Brasil',
    profissao: 'Engenheiro civil',
    renda: 18500,
    tipoLogradouro: 'Avenida',
    logradouro: 'Afonso Pena',
    numero: '1200',
    complemento: 'Sala 402',
    bairro: 'Centro',
    cidade: 'Belo Horizonte',
    estado: 'Minas Gerais',
    cep: '30130-003',
    papeis: ['locador', 'proprietario'],
  },
  {
    id: 'pes-2',
    codigo: 'P002',
    nome: 'Fernanda Oliveira Souza',
    documentoFiscal: '987.654.321-00',
    identidade: 'SP-22.101.444',
    dataNascimento: '1990-09-02',
    cidadeNascimento: 'Sao Paulo',
    pais: 'Brasil',
    profissao: 'Arquiteta',
    renda: 12400,
    tipoLogradouro: 'Rua',
    logradouro: 'Dos Pinheiros',
    numero: '88',
    complemento: 'Apto 52',
    bairro: 'Pinheiros',
    cidade: 'Sao Paulo',
    estado: 'Sao Paulo',
    cep: '05422-000',
    papeis: ['locatario'],
  },
];

export const fakeImoveis: Imovel[] = [
  {
    id: 'imo-1',
    codigo: 'IM001',
    descricaoBreve: 'Apartamento alto padrao mobiliado',
    descricaoDetalhada: 'Unidade com varanda gourmet, cozinha americana e acabamento contemporaneo.',
    valorAluguel: 4200,
    moeda: 'BRL',
    urlAnuncio: 'https://exemplo.local/imovel/im001',
    bairroLocalidade: 'Savassi',
    numeroQuartos: 3,
    tipoQuarto: 'casal suite',
    metrosQuadradosConstruidos: 118,
    tipoImovel: 'apartamento',
    tipoLavanderia: 'anexa a cozinha',
    tipoCozinha: 'americana',
    areaGourmetTipo: 'na varanda',
    areaGourmetMetrosQuadrados: 16,
    proprietarioIds: ['pes-1'],
  },
];

export const fakeAlugueis: Aluguel[] = [
  {
    id: 'alu-1',
    codigo: 'AL001',
    imovelId: 'imo-1',
    locadorId: 'pes-1',
    locatarioId: 'pes-2',
    dataInicio: '2025-01-01',
    dataFim: '2026-12-31',
    clausulaExtensaoAposPrazoOriginal: 'Renovacao automatica mediante anuencia das partes e revisao contratual.',
    valorAcordadoAluguel: 4200,
    indiceReajuste: 'IPCA',
    percentualReajuste: 6.5,
    periodos: [
      {
        id: 'per-1',
        periodo: 1,
        dataInicioPeriodo: '2025-01-01',
        dataFimPeriodo: '2025-12-31',
        valorAcordadoAluguel: 4200,
        indiceReajuste: 'IPCA',
        percentualReajuste: 6.5,
      },
    ],
  },
];
